# frozen_string_literal: true

require 'kind/core/objects/ruby/array'
require 'kind/core/objects/ruby/class'
require 'kind/core/objects/ruby/comparable'
require 'kind/core/objects/ruby/enumerable'
require 'kind/core/objects/ruby/enumerator'
require 'kind/core/objects/ruby/file'
require 'kind/core/objects/ruby/float'
require 'kind/core/objects/ruby/hash'
require 'kind/core/objects/ruby/integer'
require 'kind/core/objects/ruby/io'
require 'kind/core/objects/ruby/module'
require 'kind/core/objects/ruby/method'
require 'kind/core/objects/ruby/numeric'
require 'kind/core/objects/ruby/proc'
require 'kind/core/objects/ruby/queue'
require 'kind/core/objects/ruby/range'
require 'kind/core/objects/ruby/regexp'
require 'kind/core/objects/ruby/string'
require 'kind/core/objects/ruby/struct'
require 'kind/core/objects/ruby/symbol'
require 'kind/core/objects/ruby/time'

require 'kind/core/objects/stdlib/open_struct'
require 'kind/core/objects/stdlib/set'

require 'kind/core/objects/custom/boolean'
require 'kind/core/objects/custom/callable'
require 'kind/core/objects/custom/lambda'
