# frozen_string_literal: true

require 'kind/modules/01_checker_utils'
require 'kind/modules/02_checker_methods'
require 'kind/modules/array'
require 'kind/modules/comparable'
require 'kind/modules/enumerable'
require 'kind/modules/enumerator'
require 'kind/modules/file'
require 'kind/modules/float'
require 'kind/modules/hash'
require 'kind/modules/integer'
require 'kind/modules/io'
require 'kind/modules/method'
require 'kind/modules/numeric'
require 'kind/modules/open_struct'
require 'kind/modules/proc'
require 'kind/modules/queue'
require 'kind/modules/range'
require 'kind/modules/regexp'
require 'kind/modules/set'
require 'kind/modules/string'
require 'kind/modules/struct'
require 'kind/modules/symbol'
require 'kind/modules/time'
