# frozen_string_literal: true

require 'kind/modules/checker_utils'
require 'kind/modules/checker_methods'

require 'kind/modules/core/array'
require 'kind/modules/core/class'
require 'kind/modules/core/comparable'
require 'kind/modules/core/enumerable'
require 'kind/modules/core/enumerator'
require 'kind/modules/core/file'
require 'kind/modules/core/float'
require 'kind/modules/core/hash'
require 'kind/modules/core/integer'
require 'kind/modules/core/io'
require 'kind/modules/core/module'
require 'kind/modules/core/method'
require 'kind/modules/core/numeric'
require 'kind/modules/core/proc'
require 'kind/modules/core/queue'
require 'kind/modules/core/range'
require 'kind/modules/core/regexp'
require 'kind/modules/core/string'
require 'kind/modules/core/struct'
require 'kind/modules/core/symbol'
require 'kind/modules/core/time'

require 'kind/modules/stdlib/open_struct'
require 'kind/modules/stdlib/set'
